"""empty message

Revision ID: 7510b51f2cf0
Revises: d1c3f809bdd4
Create Date: 2020-09-22 17:29:05.442999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7510b51f2cf0'
down_revision = 'd1c3f809bdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('day_key_en', sa.String(), nullable=False),
    sa.Column('day_value_ru', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('day_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day')
    # ### end Alembic commands ###
