"""empty message

Revision ID: c445fd089691
Revises: 7510b51f2cf0
Create Date: 2020-09-23 17:22:32.606502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c445fd089691'
down_revision = '7510b51f2cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('day', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'day')
    # ### end Alembic commands ###
